"""empty message

Revision ID: 8ed254c0debb
Revises: 02daa18a023b
Create Date: 2020-06-28 14:48:23.281691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ed254c0debb'
down_revision = '02daa18a023b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('website_link', sa.String(), nullable=True))
    op.drop_column('venues', 'website')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('website', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('venues', 'website_link')
    # ### end Alembic commands ###
